//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SpaPracticeEntities : DbContext
    {
        public SpaPracticeEntities()
            : base("name=SpaPracticeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblappointment> tblappointments { get; set; }
        public virtual DbSet<tblappointmentpackagepping> tblappointmentpackageppings { get; set; }
        public virtual DbSet<tblappointmentservicemapping> tblappointmentservicemappings { get; set; }
        public virtual DbSet<tblappointmentsetting> tblappointmentsettings { get; set; }
        public virtual DbSet<tblappointmenttaxmapping> tblappointmenttaxmappings { get; set; }
        public virtual DbSet<tblavailablity> tblavailablities { get; set; }
        public virtual DbSet<tblbranch> tblbranches { get; set; }
        public virtual DbSet<tblclient> tblclients { get; set; }
        public virtual DbSet<tblcompdetail> tblcompdetails { get; set; }
        public virtual DbSet<tblcoupanmaster> tblcoupanmasters { get; set; }
        public virtual DbSet<tbldocument> tbldocuments { get; set; }
        public virtual DbSet<tblinventory> tblinventories { get; set; }
        public virtual DbSet<tblmapservice> tblmapservices { get; set; }
        public virtual DbSet<tblmaptax> tblmaptaxes { get; set; }
        public virtual DbSet<tblpackage> tblpackages { get; set; }
        public virtual DbSet<tblpackagebooking> tblpackagebookings { get; set; }
        public virtual DbSet<tblpackagedtl> tblpackagedtls { get; set; }
        public virtual DbSet<tblpaymentdtl> tblpaymentdtls { get; set; }
        public virtual DbSet<tblprintsetup> tblprintsetups { get; set; }
        public virtual DbSet<tblreport> tblreports { get; set; }
        public virtual DbSet<tblrole> tblroles { get; set; }
        public virtual DbSet<tblservice> tblservices { get; set; }
        public virtual DbSet<tblservicelog> tblservicelogs { get; set; }
        public virtual DbSet<tbltaxlog> tbltaxlogs { get; set; }
        public virtual DbSet<tbltaxmaster> tbltaxmasters { get; set; }
        public virtual DbSet<tbltherapist> tbltherapists { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
        public virtual DbSet<tblbranchright> tblbranchrights { get; set; }
        public virtual DbSet<tblcompanyright> tblcompanyrights { get; set; }
        public virtual DbSet<tblgodown> tblgodowns { get; set; }
        public virtual DbSet<tblmoduledetail> tblmoduledetails { get; set; }
        public virtual DbSet<tblmoduleright> tblmodulerights { get; set; }
        public virtual DbSet<tblbrand> tblbrands { get; set; }
        public virtual DbSet<tblitemmaingroup> tblitemmaingroups { get; set; }
        public virtual DbSet<tblitemsubgroup> tblitemsubgroups { get; set; }
        public virtual DbSet<tblsupplior> tblsuppliors { get; set; }
        public virtual DbSet<tblunit> tblunits { get; set; }
        public virtual DbSet<tblitem> tblitems { get; set; }
        public virtual DbSet<tblbatch> tblbatches { get; set; }
        public virtual DbSet<tblbomdetail> tblbomdetails { get; set; }
        public virtual DbSet<tblbomheader> tblbomheaders { get; set; }
        public virtual DbSet<tblfinancialyear> tblfinancialyears { get; set; }
        public virtual DbSet<tblitemopeningdetail> tblitemopeningdetails { get; set; }
        public virtual DbSet<tblitemopeningheader> tblitemopeningheaders { get; set; }
        public virtual DbSet<tblstock> tblstocks { get; set; }
        public virtual DbSet<tblpurchasedtl> tblpurchasedtls { get; set; }
        public virtual DbSet<tblpurchasehdr> tblpurchasehdrs { get; set; }
        public virtual DbSet<Entity1> Entity1 { get; set; }
        public virtual DbSet<tblparameter> tblparameters { get; set; }
        public virtual DbSet<tblspaparameter> tblspaparameters { get; set; }
    
        public virtual int DeleteReportData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteReportData");
        }
    
        public virtual ObjectResult<GetReportData_Result> GetReportData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReportData_Result>("GetReportData");
        }
    
        public virtual ObjectResult<GetReportDataByReportId_Result> GetReportDataByReportId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReportDataByReportId_Result>("GetReportDataByReportId");
        }
    
        public virtual int InsertReportData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertReportData");
        }
    
        public virtual ObjectResult<DailySalesReport_Result> DailySalesReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DailySalesReport_Result>("DailySalesReport");
        }
    }
}
