//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblappointmentsetting
    {
        public Nullable<int> FK_BranchID { get; set; }
        public int AppSettingId { get; set; }
        public string CalenderInterval { get; set; }
        public Nullable<bool> SendEmailDoctor { get; set; }
        public string Email { get; set; }
        public Nullable<bool> SendSMSDoctor { get; set; }
        public string Mobile { get; set; }
        public string LogoPath { get; set; }
    
        public virtual tblbranch tblbranch { get; set; }
    }
}
