//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblappointmentpackagepping
    {
        public Nullable<int> FK_BranchID { get; set; }
        public int AppointmentPackageId { get; set; }
        public Nullable<int> FK_AppointmentId { get; set; }
        public Nullable<int> FK_PackageId { get; set; }
    
        public virtual tblbranch tblbranch { get; set; }
    }
}
