//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblappointmenttaxmapping
    {
        public int Id { get; set; }
        public Nullable<int> Fk_AppointmentId { get; set; }
        public Nullable<int> Fk_TaxId { get; set; }
    
        public virtual tblappointment tblappointment { get; set; }
        public virtual tbltaxmaster tbltaxmaster { get; set; }
    }
}
