//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblappointmentservicemapping
    {
        public Nullable<int> FK_BranchID { get; set; }
        public int AppointmentServiceId { get; set; }
        public Nullable<int> FK_ServiceId { get; set; }
        public Nullable<int> FK_AppointmentId { get; set; }
    
        public virtual tblappointment tblappointment { get; set; }
        public virtual tblservice tblservice { get; set; }
        public virtual tblbranch tblbranch { get; set; }
    }
}
