//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblappointment
    {
        public tblappointment()
        {
            this.tblappointmenttaxmappings = new HashSet<tblappointmenttaxmapping>();
            this.tblpaymentdtls = new HashSet<tblpaymentdtl>();
            this.tblappointmentservicemappings = new HashSet<tblappointmentservicemapping>();
        }
    
        public Nullable<int> FK_BranchID { get; set; }
        public int AppointmentId { get; set; }
        public Nullable<int> FK_ClientId { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string AppointmentTime { get; set; }
        public Nullable<int> FK_TaxId { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> CouponDiscountAmount { get; set; }
        public Nullable<decimal> ManualDiscountPercentage { get; set; }
        public Nullable<decimal> ManualDiscountAmount { get; set; }
        public Nullable<decimal> NetPayableAmount { get; set; }
        public Nullable<decimal> PaymentDoneAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<bool> IsPaymentComplete { get; set; }
        public Nullable<int> FK_UserId { get; set; }
        public Nullable<int> FK_ServiceId { get; set; }
        public Nullable<int> FK_CouponId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PaymentType { get; set; }
        public Nullable<bool> ByPackage { get; set; }
        public Nullable<int> FK_TherapistId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public string PaymentMode { get; set; }
        public string BankCardNo_ { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<bool> IsPaymentProcessStarted { get; set; }
    
        public virtual ICollection<tblappointmenttaxmapping> tblappointmenttaxmappings { get; set; }
        public virtual ICollection<tblpaymentdtl> tblpaymentdtls { get; set; }
        public virtual tblclient tblclient { get; set; }
        public virtual tbltherapist tbltherapist { get; set; }
        public virtual tblcoupanmaster tblcoupanmaster { get; set; }
        public virtual tblbranch tblbranch { get; set; }
        public virtual tblservice tblservice { get; set; }
        public virtual tbluser tbluser { get; set; }
        public virtual ICollection<tblappointmentservicemapping> tblappointmentservicemappings { get; set; }
    }
}
