//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbranch
    {
        public tblbranch()
        {
            this.tblappointments = new HashSet<tblappointment>();
            this.tblappointmentpackageppings = new HashSet<tblappointmentpackagepping>();
            this.tblappointmentservicemappings = new HashSet<tblappointmentservicemapping>();
            this.tblappointmentsettings = new HashSet<tblappointmentsetting>();
            this.tblavailablities = new HashSet<tblavailablity>();
            this.tblpaymentdtls = new HashSet<tblpaymentdtl>();
            this.tblinventories = new HashSet<tblinventory>();
            this.tblclients = new HashSet<tblclient>();
            this.tblcompdetails = new HashSet<tblcompdetail>();
            this.tblcoupanmasters = new HashSet<tblcoupanmaster>();
            this.tbldocuments = new HashSet<tbldocument>();
            this.tblmaptaxes = new HashSet<tblmaptax>();
            this.tblpackages = new HashSet<tblpackage>();
            this.tblpackagebookings = new HashSet<tblpackagebooking>();
            this.tblreports = new HashSet<tblreport>();
            this.tblservices = new HashSet<tblservice>();
            this.tbltaxlogs = new HashSet<tbltaxlog>();
            this.tbltaxmasters = new HashSet<tbltaxmaster>();
            this.tbltherapists = new HashSet<tbltherapist>();
            this.tblusers = new HashSet<tbluser>();
            this.tblgodowns = new HashSet<tblgodown>();
        }
    
        public int BranchID { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public Nullable<bool> ActiveYN { get; set; }
        public bool HeadOfficeYN { get; set; }
    
        public virtual ICollection<tblappointment> tblappointments { get; set; }
        public virtual ICollection<tblappointmentpackagepping> tblappointmentpackageppings { get; set; }
        public virtual ICollection<tblappointmentservicemapping> tblappointmentservicemappings { get; set; }
        public virtual ICollection<tblappointmentsetting> tblappointmentsettings { get; set; }
        public virtual ICollection<tblavailablity> tblavailablities { get; set; }
        public virtual ICollection<tblpaymentdtl> tblpaymentdtls { get; set; }
        public virtual ICollection<tblinventory> tblinventories { get; set; }
        public virtual ICollection<tblclient> tblclients { get; set; }
        public virtual ICollection<tblcompdetail> tblcompdetails { get; set; }
        public virtual ICollection<tblcoupanmaster> tblcoupanmasters { get; set; }
        public virtual ICollection<tbldocument> tbldocuments { get; set; }
        public virtual ICollection<tblmaptax> tblmaptaxes { get; set; }
        public virtual ICollection<tblpackage> tblpackages { get; set; }
        public virtual ICollection<tblpackagebooking> tblpackagebookings { get; set; }
        public virtual ICollection<tblreport> tblreports { get; set; }
        public virtual ICollection<tblservice> tblservices { get; set; }
        public virtual ICollection<tbltaxlog> tbltaxlogs { get; set; }
        public virtual ICollection<tbltaxmaster> tbltaxmasters { get; set; }
        public virtual ICollection<tbltherapist> tbltherapists { get; set; }
        public virtual ICollection<tbluser> tblusers { get; set; }
        public virtual ICollection<tblgodown> tblgodowns { get; set; }
    }
}
