//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcompanyright
    {
        public int Code { get; set; }
        public int UserCd { get; set; }
        public int ComCd { get; set; }
        public bool AllowYN { get; set; }
    }
}
