//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcompdetail
    {
        public int Comp_Id { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string OwnerName { get; set; }
        public string Mobile { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public Nullable<int> FY_From { get; set; }
        public Nullable<int> FY_To { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string LogoPath { get; set; }
        public Nullable<int> FK_BranchId { get; set; }
        public string Opening_Time { get; set; }
        public string Closing_Time { get; set; }
        public Nullable<int> Interval { get; set; }
    
        public virtual tblbranch tblbranch { get; set; }
    }
}
