//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblclient
    {
        public tblclient()
        {
            this.tblappointments = new HashSet<tblappointment>();
            this.tblpackagebookings = new HashSet<tblpackagebooking>();
            this.tbldocuments = new HashSet<tbldocument>();
        }
    
        public Nullable<int> FK_BranchID { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> FK_UserId { get; set; }
        public string IdentityProofNo { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Sex { get; set; }
        public string MaritalStatus { get; set; }
        public string ReferralSource { get; set; }
        public Nullable<bool> HasMediclaim { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> SendSMS { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string CaseHistory { get; set; }
    
        public virtual ICollection<tblappointment> tblappointments { get; set; }
        public virtual tblbranch tblbranch { get; set; }
        public virtual ICollection<tblpackagebooking> tblpackagebookings { get; set; }
        public virtual tbluser tbluser { get; set; }
        public virtual ICollection<tbldocument> tbldocuments { get; set; }
    }
}
