//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcoupanmaster
    {
        public tblcoupanmaster()
        {
            this.tblappointments = new HashSet<tblappointment>();
            this.tblpaymentdtls = new HashSet<tblpaymentdtl>();
        }
    
        public Nullable<int> FK_BranchID { get; set; }
        public int Id { get; set; }
        public string Coupon_Id { get; set; }
        public string Coupan_Name { get; set; }
        public Nullable<int> Coupan_Validity { get; set; }
        public Nullable<System.DateTime> Coupan_SDateVld { get; set; }
        public Nullable<int> Coupan_NoOfUser { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Coupon_Amt { get; set; }
    
        public virtual ICollection<tblappointment> tblappointments { get; set; }
        public virtual tblbranch tblbranch { get; set; }
        public virtual ICollection<tblpaymentdtl> tblpaymentdtls { get; set; }
    }
}
