//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldocument
    {
        public Nullable<int> FK_BranchID { get; set; }
        public int DocumentId { get; set; }
        public Nullable<int> FK_ClientId { get; set; }
        public string DocumentName { get; set; }
        public string DecumentDesc { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual tblbranch tblbranch { get; set; }
        public virtual tblclient tblclient { get; set; }
    }
}
