//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfinancialyear
    {
        public int ID { get; set; }
        public byte[] FinYr { get; set; }
        public int YearSrl { get; set; }
        public bool YearLock { get; set; }
    }
}
