//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgodown
    {
        public int Code { get; set; }
        public int BranchCd { get; set; }
        public Nullable<bool> MainGodown { get; set; }
        public string Description { get; set; }
        public bool ACTIVEYN { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int UserCode { get; set; }
    
        public virtual tblbranch tblbranch { get; set; }
    }
}
