//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinventory
    {
        public int Id { get; set; }
        public string Inv_Name { get; set; }
        public string Inv_Image { get; set; }
        public string Inv_Location { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsActive { get; set; }
        public int FK_BranchId { get; set; }
    
        public virtual tblbranch tblbranch { get; set; }
    }
}
