//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblitem
    {
        public int Code { get; set; }
        public string Description { get; set; }
        public string ShortName { get; set; }
        public int SubGroupCd { get; set; }
        public int MainGroupCd { get; set; }
        public int PurchaseUnitCd { get; set; }
        public int IssueUnitCd { get; set; }
        public Nullable<decimal> UnitFactor { get; set; }
        public Nullable<decimal> ItemVatPer { get; set; }
        public Nullable<decimal> ItemVatVal { get; set; }
        public Nullable<decimal> ItemDiscPer { get; set; }
        public Nullable<decimal> ItemDiscVal { get; set; }
        public Nullable<decimal> LastPurchaseRate { get; set; }
        public Nullable<int> LastPurchaseParty { get; set; }
        public bool PerishableYN { get; set; }
        public bool SaleableYN { get; set; }
        public Nullable<decimal> ReorderLavel { get; set; }
        public bool ActiveYN { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int UserCode { get; set; }
    }
}
