//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmapservice
    {
        public int MapServiceId { get; set; }
        public Nullable<int> FK_ServiceId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> FK_BranchId { get; set; }
    
        public virtual tblservice tblservice { get; set; }
    }
}
