//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblparameter
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> AllowYN { get; set; }
        public string TranPrefixType { get; set; }
        public string TranPrefix { get; set; }
    }
}
