//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpackagedtl
    {
        public int Id { get; set; }
        public int Package_Id { get; set; }
        public int ServiceId { get; set; }
    
        public virtual tblservice tblservice { get; set; }
    }
}
