//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpackagebooking
    {
        public int PkgBookingId { get; set; }
        public Nullable<int> Fk_ClientId { get; set; }
        public Nullable<System.DateTime> PkgBookingDate { get; set; }
        public Nullable<System.DateTime> ValidityDate { get; set; }
        public Nullable<int> Fk_BranchId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Fk_PackageId { get; set; }
    
        public virtual tblbranch tblbranch { get; set; }
        public virtual tblclient tblclient { get; set; }
    }
}
