//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpackage
    {
        public int Id { get; set; }
        public string Package_Id { get; set; }
        public string Package_Name { get; set; }
        public int Package_Validity { get; set; }
        public decimal Package_Rate { get; set; }
        public Nullable<System.DateTime> Package_Creation { get; set; }
        public Nullable<int> fk_BranchID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Starting_Date { get; set; }
        public Nullable<System.DateTime> Validity_Date { get; set; }
        public string TaxID { get; set; }
    
        public virtual tblbranch tblbranch { get; set; }
    }
}
