//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpaymentdtl
    {
        public int PaymentID { get; set; }
        public Nullable<int> Fk_AppointmentId { get; set; }
        public Nullable<int> Fk_BranchId { get; set; }
        public Nullable<int> Fk_TaxId { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Mode { get; set; }
        public string Bank_CardNo { get; set; }
        public string Bank_Name { get; set; }
        public Nullable<int> Fk_CouponID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> Total_Amt { get; set; }
        public Nullable<decimal> Service_Amt { get; set; }
        public Nullable<decimal> Tax_Amt { get; set; }
        public Nullable<decimal> Discount_Amt { get; set; }
        public Nullable<decimal> Net_Amt { get; set; }
        public Nullable<decimal> Advance_Amt { get; set; }
        public Nullable<decimal> Due_Amt { get; set; }
        public Nullable<decimal> Received_Amt { get; set; }
        public Nullable<bool> IsPaymentComplete { get; set; }
    
        public virtual tblappointment tblappointment { get; set; }
        public virtual tblbranch tblbranch { get; set; }
        public virtual tblcoupanmaster tblcoupanmaster { get; set; }
        public virtual tbltaxmaster tbltaxmaster { get; set; }
    }
}
