//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstock
    {
        public int Code { get; set; }
        public int TransuctionHdCd { get; set; }
        public int TransuctionDtlCd { get; set; }
        public System.DateTime StockDate { get; set; }
        public int ItemCd { get; set; }
        public int UnitCd { get; set; }
        public decimal StockQty { get; set; }
        public int StockUnitCd { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string StockType { get; set; }
        public int ReferenceID { get; set; }
        public Nullable<int> BranchCD { get; set; }
        public Nullable<int> GodownCD { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int UserCode { get; set; }
    }
}
