//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblservice
    {
        public tblservice()
        {
            this.tblappointments = new HashSet<tblappointment>();
            this.tblappointmentservicemappings = new HashSet<tblappointmentservicemapping>();
            this.tblavailablities = new HashSet<tblavailablity>();
            this.tblmapservices = new HashSet<tblmapservice>();
            this.tblpackagedtls = new HashSet<tblpackagedtl>();
            this.tblservicelogs = new HashSet<tblservicelog>();
        }
    
        public Nullable<int> FK_BranchID { get; set; }
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> FK_UserId { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public string TaxID { get; set; }
        public Nullable<int> TimeExpende { get; set; }
    
        public virtual ICollection<tblappointment> tblappointments { get; set; }
        public virtual ICollection<tblappointmentservicemapping> tblappointmentservicemappings { get; set; }
        public virtual ICollection<tblavailablity> tblavailablities { get; set; }
        public virtual tblbranch tblbranch { get; set; }
        public virtual ICollection<tblmapservice> tblmapservices { get; set; }
        public virtual ICollection<tblpackagedtl> tblpackagedtls { get; set; }
        public virtual tbluser tbluser { get; set; }
        public virtual ICollection<tblservicelog> tblservicelogs { get; set; }
    }
}
