//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltaxmaster
    {
        public tbltaxmaster()
        {
            this.tblappointmenttaxmappings = new HashSet<tblappointmenttaxmapping>();
            this.tblmaptaxes = new HashSet<tblmaptax>();
            this.tblpaymentdtls = new HashSet<tblpaymentdtl>();
            this.tbltaxlogs = new HashSet<tbltaxlog>();
        }
    
        public Nullable<int> FK_BranchID { get; set; }
        public int Tax_Id { get; set; }
        public string Tax_Name { get; set; }
        public Nullable<decimal> Tax_Rate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<tblappointmenttaxmapping> tblappointmenttaxmappings { get; set; }
        public virtual tblbranch tblbranch { get; set; }
        public virtual ICollection<tblmaptax> tblmaptaxes { get; set; }
        public virtual ICollection<tblpaymentdtl> tblpaymentdtls { get; set; }
        public virtual ICollection<tbltaxlog> tbltaxlogs { get; set; }
    }
}
