//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltherapist
    {
        public tbltherapist()
        {
            this.tblappointments = new HashSet<tblappointment>();
        }
    
        public int TherapistId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Specialist { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Availability { get; set; }
        public string Days { get; set; }
        public Nullable<bool> Leave { get; set; }
        public string Timings { get; set; }
        public string TherapistLeave { get; set; }
        public Nullable<int> FK_BranchId { get; set; }
    
        public virtual ICollection<tblappointment> tblappointments { get; set; }
        public virtual tblbranch tblbranch { get; set; }
    }
}
