//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public tbluser()
        {
            this.tblappointments = new HashSet<tblappointment>();
            this.tblavailablities = new HashSet<tblavailablity>();
            this.tblclients = new HashSet<tblclient>();
            this.tblservices = new HashSet<tblservice>();
        }
    
        public Nullable<int> FK_BranchID { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> FK_RoleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Mobile { get; set; }
    
        public virtual ICollection<tblappointment> tblappointments { get; set; }
        public virtual ICollection<tblavailablity> tblavailablities { get; set; }
        public virtual tblbranch tblbranch { get; set; }
        public virtual ICollection<tblclient> tblclients { get; set; }
        public virtual tblrole tblrole { get; set; }
        public virtual ICollection<tblservice> tblservices { get; set; }
    }
}
